### ISSUE TITLE
the raw semantic KITTI data does not include png data,need I preprocess the .bin into png?

### ISSUE THREAD

**Issue by LeopoldACC** [Jiang-Muyun/PointNet12#2]
the wrong information is like below,thks!
```
Traceback (most recent call last):
  File "pcdvis.py", line 154, in <module>
    vis(args)
  File "pcdvis.py", line 116, in vis
    point_cloud, label = kitti_utils.get(part, index, load_image=True)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/kitti_utils.py", line 190, in get
    assert os.path.exists(fn_frame), 'Broken dataset %s' % (fn_frame)
AssertionError: Broken dataset /home/gz/桌面/3DCVcode/segmentation/SemanticKITTI/data/dataset/dataset/sequences/01/image_2/000000.png
```

**Comment by Jiang-Muyun** [comment]
Please download the KITTI odometry dataset [http://www.cvlibs.net/datasets/kitti/eval_odometry.php] (color, 65 GB) and unzip it along with the Semantic KITTI label files. PNG files are camera images, just for a better visualization, not actually need for point cloud segmenations.

**Comment by LeopoldACC** [comment]
thks for answering ! I can not download from the source link https://s3.eu-central-1.amazonaws.com/avg-kitti/data_odometry_color.zip due to the ban of net from US to CH,so I download from the baiduyun link,but the label file is not included,I download the potential label file from another baiduyun link,but it just include "000000.txt",I run the code and show the bug below
```
Traceback (most recent call last):
  File "pcdvis.py", line 154, in <module>
    vis(args)
  File "pcdvis.py", line 116, in vis
    point_cloud, label = kitti_utils.get(part, index, load_image=True)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/kitti_utils.py", line 198, in get
    assert os.path.exists(fn_label), 'Broken dataset %s' % (fn_label)
AssertionError: Broken dataset ../data/sequences/01/labels/000000.label
```
I will preciate that if you can upload the whole dataset to baiduyun or other link that I can download!

**Comment by LeopoldACC** [comment]
My first promblem has been solved,but when I run `pcd_seg.py`,and **the dataloader will run the redis to fetch data**,in which process the **redis connection failed**,I search the website to find potential method to solve it.Their anwser is to start the redis,but they installed the redis not as python package,so **what should i do to start the redis in pythonic way**?Thanks!
```python
Traceback (most recent call last):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/__main__.py", line 45, in <module>
    cli.main()
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 444, in main
    run()
  File "/home/gz/.vscode/extensions/ms-python.python-2021.3.680753044/pythonFiles/lib/python/debugpy/../debugpy/server/cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 242, in <module>
    evaluate(args)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 229, in evaluate
    acc, miou = test_kitti_semseg(model.eval(), testdataloader,args.model_name,num_classes,class_names)
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/pcdseg.py", line 64, in test_kitti_semseg
    for points, target in tqdm(loader, total=len(loader), smoothing=0.9, dynamic_ncols=True):
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/tqdm/std.py", line 1166, in __iter__
    for obj in iterable:
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 475, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/SemKITTI_Loader.py", line 92, in __getitem__
    point_cloud, label = self.get_data(self.keys[index])
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/SemKITTI_Loader.py", line 77, in get_data
    if not self.np_redis.exists(key):
  File "/home/gz/桌面/3DCVcode/segmentation/PointNet12KiTTI/data_utils/redis_utils.py", line 49, in exists
    return bool(self.handle.execute_command('EXISTS ' + key))
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 1192, in get_connection
    connection.connect()
  File "/home/gz/anaconda3/envs/pc/lib/python3.8/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```
I found the [https://pypi.org/project/redis/](https://pypi.org/project/redis/) show the information below.
```
Installation
redis-py requires a running Redis server. See Redis’s quickstart for installation instructions.
```
I found reason is that I didn't install the redis lol.If anyone condition like me,can follow the [pipeline of install tutorial](https://redis.io/topics/quickstart) to make file first and start redis-server firstly.

**Comment by LeopoldACC** [comment]
@Jiang-Muyun  
hi,Muyun,I'm confused about the train_dataset setting is just a half of the data,is that include specific meaning?thks!
just show as below **`for index in range(0,length,2):`**
```python
class SemKITTI_Loader(Dataset):
    def __init__(self, root, npoints, train = True, subset = 'all'):
        self.root = root
        self.train = train
        self.npoints = npoints
        self.np_redis = Mat_Redis_Utils()
        self.utils = Semantic_KITTI_Utils(root,subset)

        part_length = {'00': 4540,'01':1100,'02':4660,'03':800,'04':270,'05':2760,
            '06':1100,'07':1100,'08':4070,'09':1590,'10':1200}

        self.keys = []
        alias = subset[0]
        
        if self.train:
            for part in ['00','01','02','03','04','05','06','07','09','10']:
                length = part_length[part]
                for index in range(0,length,2):
                    self.keys.append('%s/%s/%06d'%(alias, part, index))
```

- Another question is that the way of calculating miou,why ignore the first class as shown as below,can we ignore the car class?
```python
miou = np.mean(categorical_iou[1:])
```

**Comment by Jiang-Muyun** [comment]
Dear Leopold,
For the first question, maybe it's because the dataset is too large and I want to cut the size by half, because the neighbor frames are basically the same.

For the second question, I want to ignore the background class, for multi-class categorical IoU, I think we don't need to consider the IoU of the background class.

Sorry, I have not been doing this project for a long time, some of my memories are blurry.

**Comment by LeopoldACC** [comment]
Thanks for answering!
I got the first problem.
But the second problem is that is setting the iou of class not included in a pointcloud to 1 reasonable?
```python
for class_id in range(num_classes):
    I = torch.sum((pred_choice == class_id) & (target == class_id)).cpu().item()
    U = torch.sum((pred_choice == class_id) | (target == class_id)).cpu().item()
    iou = 1 if U == 0 else I/U
    ious[class_id] += iou
    count[class_id] += 1
```
I print the class_names as below
```
miou = np.mean(categorical_iou[1:])
class_names = ['car', 'bicycle', 'motorcycle', 'truck', 'other-vehicle', 'person', 'bicyclist', 'motorcyclist', 'road', 'parking', 'sidewalk', 'other-ground', 'building', 'fence', 'vegetation', 'trunk', 'terrain', 'pole', 'traffic-sign']
```
**so the first class car may be ignored?**
is the change as the code below is available?
```python
Is = {i:0 for i in range(num_classes)}
Us = {i:0 for i in range(num_classes)}
for class_id in range(num_classes):
    Is[class_id] += torch.sum((pred_choice == class_id) & (target == class_id)).cpu().item()
    Us[class_id] += torch.sum((pred_choice == class_id) | (target == class_id)).cpu().item()
IoUs = {i:Is[i]/Us[i] for i in range(num_classes) if Us[i]!=0 else -1}
valid_IoUs = [v for k,v in IoUs if v!=-1]
mIoU = np.mean(valid_IoUs)
```
Thanks!

**Comment by chaojiwuliaoa** [comment]
Hello,Can you show me the layout format of the KITTI file? My file layout keeps reporting errors, which makes me so vexed.

**Comment by Nicoleperry** [comment]
Dear Jiang-Muyun，
I've already set the load_image parameter to False, but why am I still encountering this issue?
    def get(self, part, index, load_image =False):




(pointnet12_env) (base) zyt@zyt-Legion-Y9000X-IAH7:~/pointnet12_env$ KITTI_ROOT=/home/zyt/kitti00_label python /home/zyt/pointnet12_env/src/pcdvis.py
[Open3D WARNING] Read JSON failed: unable to open file: config/ego_view.json
[Open3D WARNING] Read JSON failed: unable to open file: config/render_option.json
>  ... 0 (25000,)[349 ms]
[Open3D WARNING] [ViewControl] ConvertFromPinholeCameraParameters() failed because window height and width do not match.
Traceback (most recent call last):
  File "/home/zyt/pointnet12_env/src/pcdvis.py", line 155, in <module>
    vis(args)
  File "/home/zyt/pointnet12_env/src/pcdvis.py", line 145, in vis
    sem_img = kitti_utils.draw_2d_points(pts_2d, kitti_utils.colors_bgr[pred])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zyt/pointnet12_env/src/data_utils/kitti_utils.py", line 374, in draw_2d_points
    image = self.frame.copy()
            ^^^^^^^^^^
AttributeError: 'Semantic_KITTI_Utils' object has no attribute 'frame'
